Provides a tuneable argument 'timeout' for the web socket
jjlawren/sonos-websocket pull request #26
Opened 2024-01-07 23:02 UTC by ciaranj

As described in #7 the wss connect timeout can sometimes be a little low. I'm unsure why, but it isn't a network stability issue as suggested in the existing issue.

This patch will allow upstream consumers of the library to be less aggressive with the timeouts should they want to be, but I've left the default at 3 seconds for consistency.

2024-01-09 03:08 UTC, jjlawren requested changes
Thanks for testing and suggesting an improvement. It feels like a Sonos firmware limitation where older speakers need a bit more time to complete the operation.

Here are a couple of minor suggestions. Let's just default to the longer timeout. The original 3s was chosen arbitrarily as it worked well in my local setup.

2024-01-09 03:08 UTC, jjlawren commented on sonos_websocket/websocket.py
> +        timeout: int | None = None
Let's just set the default here:
```suggestion
        timeout: int = 6
```

2024-01-09 03:08 UTC, jjlawren commented on sonos_websocket/websocket.py
> +        self._timeout = timeout if timeout else 3
```suggestion
        self._timeout = timeout
```

2024-01-09 15:08 UTC, ciaranj commented
Thanks for the improvements @jjlawren, python is not my strongest language (by far) so I was kinda guessing at what 'best practice' was around default values on keyword arguments was! 

3s feels like an *age* to create the connection and should have been acceptable, but 6s seems to give a much better success-rate for me on my kit on a solid network \o/

2024-01-09 23:50 UTC, jjlawren commented
There are CI checks which are failing. I've just added a couple rule exemptions for `pylint` and merged in from `main`. If you can apply the `ruff-format` suggestions it should pass fine.

2024-01-10 22:24 UTC, ciaranj commented
@jjlawren I'll make the changes, but this one: 

diff --git a/sonos_websocket/websocket.py b/sonos_websocket/websocket.py
index 4c24492..b0a37da 100644
--- a/sonos_websocket/websocket.py
+++ b/sonos_websocket/websocket.py
@@ -33,7 +33,7 @@ class SonosWebsocket:
         player_id: str | None = None,
         household_id: str | None = None,
         session: aiohttp.ClientSession | None = None,
-        timeout: int = 6
+        timeout: int = 6,
     ) -> None:
         """Initialize the websocket instance."""
         self.uri = f"wss://{ip_addr}:14[43](https://github.com/jjlawren/sonos-websocket/actions/runs/7468287779/job/20323430305?pr=26#step:6:44)/websocket/api"

goes against all that is right in this world, what sort of monsters require trailing commas in function argument definitions (again, not a pythonista, but literally that *only* reason I could see this being mandated would be to maybe improve diffs overtime.. Super weird to my eyes!

2024-01-11 01:11 UTC, jjlawren commented
Correct, it's mostly to avoid future diffs if the arguments (or similar data structures) are amended over time. See the PEP8 style guide [here](https://peps.python.org/pep-0008/#when-to-use-trailing-commas) for details.

2024-01-11 01:33 UTC, jjlawren approved these changes
Looks good, thanks for the contribution!

2024-01-11 01:34 UTC, merged